import type { BusinessTemplate, TemplateTask } from "./types.js";
import { chiefOfStaffTask } from "./common.js";

// Content/creator business (newsletter, YouTube, podcast, course creator).
// Not one of Part 2's three canonical examples, but derived the same way
// from the catalog: CMO is the heart (content IS the product), CFO lite
// around sponsorship/ad revenue, Support for the audience/community, and a
// light Sales presence for brand-deal outreach. No Ops/fulfillment.
const tasks: TemplateTask[] = [
  chiefOfStaffTask,

  // CMO — the heart
  {
    id: "cmo.content.longform",
    text: "Draft long-form content in the creator's voice (scripts, newsletter issues, articles)",
    subAgentType: "content-writer",
    subAgentLabel: "Content writer",
    teamHint: "cmo",
    frequency: "daily",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    handsTool: null,
  },
  {
    id: "cmo.social.clips",
    text: "Draft platform-sized clips/posts promoting each piece of content",
    subAgentType: "social-manager",
    subAgentLabel: "Social manager",
    teamHint: "cmo",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Instagram/TikTok",
  },
  {
    id: "cmo.seo.growth",
    text: "Keyword and content-gap research to grow organic reach",
    subAgentType: "seo-agent",
    subAgentLabel: "SEO agent",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "recommendations",
    handsTool: null,
  },
  {
    id: "cmo.email.newsletter",
    text: "Draft newsletter sends and list-hygiene flags",
    subAgentType: "email-marketing",
    subAgentLabel: "Email marketing",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Resend/ConvertKit",
  },
  {
    id: "cmo.ad.sponsorcopy",
    text: "Draft sponsorship/ad-read copy variants",
    subAgentType: "ad-creative",
    subAgentLabel: "Ad-creative",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "spend",
    handsTool: null,
  },

  // CFO — lite, sponsorship/ad-revenue focus
  {
    id: "cfo.invoicing.sponsors",
    text: "Create invoices for sponsorships/brand deals",
    subAgentType: "invoicing",
    subAgentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Stripe",
  },
  {
    id: "cfo.invoicing.remind",
    text: "Draft payment reminders for sponsors",
    subAgentType: "invoicing",
    subAgentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Stripe",
  },
  {
    id: "cfo.expenses.categorize",
    text: "Tag expenses (equipment, software, contractors) and flag anomalies",
    subAgentType: "expense-categorization",
    subAgentLabel: "Expense categorization",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10 approvals",
    handsTool: null,
  },
  {
    id: "cfo.cashflow.forecast",
    text: "Project revenue across ad/sponsor/subscription income",
    subAgentType: "cashflow-forecast",
    subAgentLabel: "Cash-flow forecast",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "reports only",
    handsTool: null,
  },

  // Support — audience/community
  {
    id: "support.triage.inbound",
    text: "Read inbound audience messages/comments, tag urgency, draft replies to known questions",
    subAgentType: "tier1-triage",
    subAgentLabel: "Tier-1 triage",
    teamHint: "support",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "known-answer replies",
    handsTool: "Shared inbox",
  },
  {
    id: "support.community.onboarding",
    text: "Draft community onboarding and check-in messages",
    subAgentType: "onboarding",
    subAgentLabel: "Onboarding",
    teamHint: "support",
    frequency: "weekly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Discord",
  },

  // Sales — light, brand deals only
  {
    id: "sales.outreach.brand",
    text: "Draft personalized brand-partnership outreach and follow-ups",
    subAgentType: "outreach-drafter",
    subAgentLabel: "Outreach drafter",
    teamHint: "sales",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "sending, always",
    handsTool: "Email",
  },
  {
    id: "sales.crm.sponsors",
    text: "Log sponsor interactions and flag stale deals",
    subAgentType: "crm-hygiene",
    subAgentLabel: "CRM hygiene",
    teamHint: "sales",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10",
    handsTool: "CRM",
  },
];

export const contentTemplate: BusinessTemplate = {
  id: "content",
  name: "Content / creator business",
  description: "A business whose product is the content itself (newsletter, YouTube, podcast, course creator).",
  tasks,
};
