import type { BusinessTemplate, TemplateTask } from "./types.js";
import { chiefOfStaffTask } from "./common.js";

// Physical-goods / e-commerce (marketplace or own storefront). Per Part 2's
// example instantiation ("handmade candle shop on Etsy"): CFO lite,
// CMO with content/social/email and minimal SEO, Ops heavy on
// inventory/fulfillment, Support lite, and deliberately NO Sales team —
// marketplace/storefront traffic handles demand generation.
const tasks: TemplateTask[] = [
  chiefOfStaffTask,

  // CFO — lite
  {
    id: "cfo.invoicing.create",
    text: "Create invoices/receipts for orders",
    agentType: "invoicing",
    agentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "daily",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Stripe",
    cadence: "daily",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.invoicing.remind",
    text: "Draft payment reminders matched to customer history",
    agentType: "invoicing",
    agentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Stripe",
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "cfo.expenses.categorize",
    text: "Tag every transaction and flag anomalies",
    agentType: "expense-categorization",
    agentLabel: "Expense categorization",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10 approvals",
    handsTool: "Stripe",
    cadence: "nightly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.cashflow.forecast",
    text: "30/60/90-day cash-flow projection with runway alerts",
    agentType: "cashflow-forecast",
    agentLabel: "Cash-flow forecast",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "reports only",
    handsTool: null,
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cfo.tax.tracker",
    text: "Track tax deadlines and prep the document checklist",
    agentType: "tax-deadline-tracker",
    agentLabel: "Tax-deadline tracker",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T1",
    autonomy: "locked",
    handsTool: null,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // CMO — content/social/email, SEO minimal
  {
    id: "cmo.social.posts",
    text: "Draft platform-sized social posts for the shop (Instagram, Pinterest, TikTok)",
    agentType: "social-manager",
    agentLabel: "Social manager",
    teamHint: "cmo",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "posting stays locked",
    handsTool: "Instagram/Meta",
    cadence: "daily",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cmo.content.blog",
    text: "Write occasional blog/newsletter content in brand voice",
    agentType: "content-writer",
    agentLabel: "Content writer",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: null,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cmo.email.campaigns",
    text: "Draft email marketing sequences and campaign copy",
    agentType: "email-marketing",
    agentLabel: "Email marketing",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Resend",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cmo.seo.listings",
    text: "Light keyword and listing-title research for marketplace SEO",
    agentType: "seo-agent",
    agentLabel: "SEO agent",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "reports",
    handsTool: null,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // Ops — inventory/fulfillment heavy
  {
    id: "ops.inventory.levels",
    text: "Track stock levels per product/SKU",
    agentType: "inventory",
    agentLabel: "Inventory",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "alerts",
    handsTool: "Shopify/Etsy",
    cadence: "daily",
    batchable: true,
    triggerType: "threshold",
  },
  {
    id: "ops.inventory.reorder",
    text: "Flag reorder points for raw materials and packaging",
    agentType: "inventory",
    agentLabel: "Inventory",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "medium",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "alerts",
    handsTool: "Shopify/Etsy",
    cadence: "weekly",
    batchable: true,
    triggerType: "threshold",
  },
  {
    id: "ops.fulfillment.status",
    text: "Post order status and shipping updates to customers",
    agentType: "fulfillment",
    agentLabel: "Fulfillment/logistics",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "status updates",
    handsTool: "Shipping carrier",
    cadence: "daily",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "ops.fulfillment.delay",
    text: "Draft delay/backorder communications",
    agentType: "fulfillment",
    agentLabel: "Fulfillment/logistics",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "medium",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Shipping carrier",
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "ops.vendor.tracking",
    text: "Track supplier orders for raw materials",
    agentType: "vendor-manager",
    agentLabel: "Vendor manager",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: null,
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "ops.vendor.comms",
    text: "Draft reorder communications to vendors",
    agentType: "vendor-manager",
    agentLabel: "Vendor manager",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "ordering never autonomous",
    handsTool: null,
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },

  // Support — lite
  {
    id: "support.triage.inbound",
    text: "Read inbound customer messages, tag urgency/topic, draft replies to known questions",
    agentType: "tier1-triage",
    agentLabel: "Tier-1 triage",
    teamHint: "support",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "known-answer replies",
    handsTool: "Shared inbox",
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "support.escalation.detect",
    text: "Detect angry or complex cases and package context for the human",
    agentType: "escalation",
    agentLabel: "Escalation",
    teamHint: "support",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "always routes to human",
    handsTool: null,
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
];

export const ecommerceTemplate: BusinessTemplate = {
  id: "ecommerce",
  name: "E-commerce / physical goods",
  description:
    "Selling physical products online (own storefront or a marketplace like Etsy/Shopify).",
  tasks,
  branchQuestions: [
    {
      id: "inventoryModel",
      prompt: "Do you hold your own inventory, or is it dropshipped/print-on-demand?",
      kind: "single-select",
      options: [
        { value: "own-inventory", label: "I hold my own inventory" },
        { value: "dropship-or-pod", label: "Dropshipped or print-on-demand" },
        { value: "mixed", label: "A mix of both" },
      ],
    },
    {
      id: "sellsThrough",
      prompt: "Where do you sell?",
      kind: "single-select",
      options: [
        { value: "own-storefront", label: "My own storefront" },
        { value: "marketplace", label: "A marketplace (Etsy, Amazon...)" },
        { value: "both", label: "Both" },
      ],
    },
  ],
};
