import type { BusinessTemplate, TemplateTask } from "./types.js";
import { chiefOfStaffTask } from "./common.js";

// Local brick-and-mortar (shop, cafe, salon — foot-traffic driven, often
// with staff). Derived from the catalog's general patterns: CFO with
// payroll prep, CMO focused on local/Google-Business presence, Ops heavy
// on scheduling/vendor/inventory via a POS, Support for calls/DMs, and a
// People Lead for hiring since brick-and-mortar businesses commonly staff up.
const tasks: TemplateTask[] = [
  chiefOfStaffTask,

  // CFO
  {
    id: "cfo.invoicing.create",
    text: "Create invoices/receipts for larger local orders",
    subAgentType: "invoicing",
    subAgentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Square",
  },
  {
    id: "cfo.expenses.categorize",
    text: "Tag daily expenses and flag anomalies",
    subAgentType: "expense-categorization",
    subAgentLabel: "Expense categorization",
    teamHint: "cfo",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10 approvals",
    handsTool: "Square",
  },
  {
    id: "cfo.cashflow.forecast",
    text: "30/60/90-day cash-flow projection with runway alerts",
    subAgentType: "cashflow-forecast",
    subAgentLabel: "Cash-flow forecast",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "reports only",
    handsTool: null,
  },
  {
    id: "cfo.tax.tracker",
    text: "Track tax deadlines and local business license renewals",
    subAgentType: "tax-deadline-tracker",
    subAgentLabel: "Tax-deadline tracker",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T1",
    autonomy: "locked",
    handsTool: null,
  },
  {
    id: "cfo.payroll.prep",
    text: "Summarize staff hours and prep the payroll-run checklist",
    subAgentType: "payroll-prep",
    subAgentLabel: "Payroll prep",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    handsTool: "Payroll provider",
  },

  // CMO — local presence
  {
    id: "cmo.social.local",
    text: "Draft local social posts (offers, events, new arrivals)",
    subAgentType: "social-manager",
    subAgentLabel: "Social manager",
    teamHint: "cmo",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Instagram/Facebook",
  },
  {
    id: "cmo.seo.googlebusiness",
    text: "Keep the Google Business listing and local SEO fresh",
    subAgentType: "seo-agent",
    subAgentLabel: "SEO agent",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: "Google Business",
  },
  {
    id: "cmo.email.promos",
    text: "Draft email/SMS promos for regulars",
    subAgentType: "email-marketing",
    subAgentLabel: "Email marketing",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Resend",
  },

  // Ops — scheduling/vendor/inventory, POS-heavy
  {
    id: "ops.scheduling.shifts",
    text: "Manage staff shift calendar and appointment bookings",
    subAgentType: "scheduling",
    subAgentLabel: "Scheduling",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Calendar",
  },
  {
    id: "ops.vendor.tracking",
    text: "Track supplier/vendor orders and flag reorder points",
    subAgentType: "vendor-manager",
    subAgentLabel: "Vendor manager",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: "POS",
  },
  {
    id: "ops.vendor.comms",
    text: "Draft vendor reorder communications",
    subAgentType: "vendor-manager",
    subAgentLabel: "Vendor manager",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "medium",
    tier: "T1",
    autonomy: "locked",
    autonomyNote: "ordering never autonomous",
    handsTool: "POS",
  },
  {
    id: "ops.inventory.levels",
    text: "Track in-store stock levels and reorder-point alerts",
    subAgentType: "inventory",
    subAgentLabel: "Inventory",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "alerts",
    handsTool: "POS",
  },

  // Support
  {
    id: "support.triage.inbound",
    text: "Read inbound calls/messages/DMs, tag urgency, draft replies to known questions",
    subAgentType: "tier1-triage",
    subAgentLabel: "Tier-1 triage",
    teamHint: "support",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "known-answer replies",
    handsTool: "Shared inbox",
  },
  {
    id: "support.escalation.detect",
    text: "Detect upset customers or complex cases and package context for the human",
    subAgentType: "escalation",
    subAgentLabel: "Escalation",
    teamHint: "support",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "always routes to human",
    handsTool: null,
  },

  // People — hiring signals common for staffed local businesses
  {
    id: "people.jobpost.write",
    text: "Draft job posts when hiring signals appear",
    subAgentType: "job-post-writer",
    subAgentLabel: "Job-post writer",
    teamHint: "people",
    frequency: "adhoc",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    handsTool: null,
  },
  {
    id: "people.applicant.summarize",
    text: "Summarize applicants for human screening",
    subAgentType: "applicant-summarizer",
    subAgentLabel: "Applicant summarizer",
    teamHint: "people",
    frequency: "adhoc",
    stakes: "medium",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "assists screening, never auto-rejects — the human decides",
    handsTool: null,
  },
];

export const localTemplate: BusinessTemplate = {
  id: "local",
  name: "Local brick-and-mortar",
  description: "A foot-traffic-driven local business (shop, cafe, salon), often with staff.",
  tasks,
};
