import type { BusinessTemplate, TemplateTask } from "./types.js";
import { chiefOfStaffTask } from "./common.js";

// Local brick-and-mortar (shop, cafe, salon — foot-traffic driven, often
// with staff). Derived from the catalog's general patterns: CFO with
// payroll prep, CMO focused on local/Google-Business presence, Ops heavy
// on scheduling/vendor/inventory via a POS, Support for calls/DMs, and a
// People Lead for hiring since brick-and-mortar businesses commonly staff up.
const tasks: TemplateTask[] = [
  chiefOfStaffTask,

  // CFO
  {
    id: "cfo.invoicing.create",
    text: "Create invoices/receipts for larger local orders",
    agentType: "invoicing",
    agentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Square",
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.expenses.categorize",
    text: "Tag daily expenses and flag anomalies",
    agentType: "expense-categorization",
    agentLabel: "Expense categorization",
    teamHint: "cfo",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10 approvals",
    handsTool: "Square",
    cadence: "nightly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.cashflow.forecast",
    text: "30/60/90-day cash-flow projection with runway alerts",
    agentType: "cashflow-forecast",
    agentLabel: "Cash-flow forecast",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "reports only",
    handsTool: null,
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cfo.tax.tracker",
    text: "Track tax deadlines and local business license renewals",
    agentType: "tax-deadline-tracker",
    agentLabel: "Tax-deadline tracker",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T1",
    autonomy: "locked",
    handsTool: null,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cfo.payroll.prep",
    text: "Summarize staff hours and prep the payroll-run checklist",
    agentType: "payroll-prep",
    agentLabel: "Payroll prep",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    handsTool: "Payroll provider",
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },

  // CMO — local presence
  {
    id: "cmo.social.local",
    text: "Draft local social posts (offers, events, new arrivals)",
    agentType: "social-manager",
    agentLabel: "Social manager",
    teamHint: "cmo",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Instagram/Facebook",
    cadence: "daily",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cmo.seo.googlebusiness",
    text: "Keep the Google Business listing and local SEO fresh",
    agentType: "seo-agent",
    agentLabel: "SEO agent",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: "Google Business",
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cmo.email.promos",
    text: "Draft email/SMS promos for regulars",
    agentType: "email-marketing",
    agentLabel: "Email marketing",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Resend",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },

  // Ops — scheduling/vendor/inventory, POS-heavy
  {
    id: "ops.scheduling.shifts",
    text: "Manage staff shift calendar and appointment bookings",
    agentType: "scheduling",
    agentLabel: "Scheduling",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Calendar",
    cadence: "daily",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "ops.vendor.tracking",
    text: "Track supplier/vendor orders and flag reorder points",
    agentType: "vendor-manager",
    agentLabel: "Vendor manager",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: "POS",
    cadence: "weekly",
    batchable: true,
    triggerType: "threshold",
  },
  {
    id: "ops.vendor.comms",
    text: "Draft vendor reorder communications",
    agentType: "vendor-manager",
    agentLabel: "Vendor manager",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "medium",
    // T2, matching ecommerce.ts's identical task id: drafting an external
    // communication is consistently T2 everywhere else in the catalog
    // (invoicing reminders, outreach drafts, onboarding sequences) — this
    // was T1 here with no stated reason, found by the cross-template tier
    // audit (2026-08-06). See tests/consistency.test.ts for the regression
    // guard.
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "ordering never autonomous",
    handsTool: "POS",
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "ops.inventory.levels",
    text: "Track in-store stock levels and reorder-point alerts",
    agentType: "inventory",
    agentLabel: "Inventory",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "alerts",
    handsTool: "POS",
    cadence: "daily",
    batchable: true,
    triggerType: "threshold",
  },

  // Support
  {
    id: "support.triage.inbound",
    text: "Read inbound calls/messages/DMs, tag urgency, draft replies to known questions",
    agentType: "tier1-triage",
    agentLabel: "Tier-1 triage",
    teamHint: "support",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "known-answer replies",
    handsTool: "Shared inbox",
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "support.escalation.detect",
    text: "Detect upset customers or complex cases and package context for the human",
    agentType: "escalation",
    agentLabel: "Escalation",
    teamHint: "support",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "always routes to human",
    handsTool: null,
    cadence: null,
    batchable: false,
    triggerType: "event",
  },

  // People — hiring signals common for staffed local businesses
  {
    id: "people.jobpost.write",
    text: "Draft job posts when hiring signals appear",
    agentType: "job-post-writer",
    agentLabel: "Job-post writer",
    teamHint: "people",
    frequency: "adhoc",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    handsTool: null,
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "people.applicant.summarize",
    text: "Summarize applicants for human screening",
    agentType: "applicant-summarizer",
    agentLabel: "Applicant summarizer",
    teamHint: "people",
    frequency: "adhoc",
    stakes: "medium",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "assists screening, never auto-rejects — the human decides",
    handsTool: null,
    cadence: null,
    batchable: true,
    triggerType: "event",
  },
];

export const localTemplate: BusinessTemplate = {
  id: "local",
  name: "Local brick-and-mortar",
  description: "A foot-traffic-driven local business (shop, cafe, salon), often with staff.",
  tasks,
  branchQuestions: [
    {
      id: "staffing",
      prompt: "Do you have staff beyond yourself?",
      kind: "single-select",
      options: [
        { value: "solo", label: "Just me" },
        { value: "a-few-staff", label: "A few staff" },
        { value: "many-staff", label: "A larger staff" },
      ],
    },
    {
      id: "customerFlow",
      prompt: "Do customers walk in or book ahead?",
      kind: "single-select",
      options: [
        { value: "walk-in", label: "Walk-in" },
        { value: "appointments", label: "Appointments" },
        { value: "both", label: "Both" },
      ],
    },
  ],
};
