import type { BusinessTemplate, TemplateTask } from "./types.js";
import { chiefOfStaffTask } from "./common.js";

// Physical-space membership business (gyms, makerspaces, coworking, studios,
// climbing gyms). Added from the makerspace fixture findings (GitHub issue
// "Template improvements from makerspace fixture findings"): a business
// built around a shared physical resource — memberships, bookings/rentals,
// events/classes, facility upkeep, and safety/waivers — doesn't map cleanly
// onto ecommerce (no physical goods shipped) or local (no single-visit
// storefront transaction model). Membership/rental billing is genuinely the
// business's own revenue (cfo); scheduling and facility upkeep are genuinely
// ops's job — this template does NOT need a "delivery" team, unlike service.
const tasks: TemplateTask[] = [
  chiefOfStaffTask,

  // CFO — membership/rental billing IS the business's own revenue, not a
  // client-facing "delivery" — no rescue needed, cfo is correct here.
  {
    id: "cfo.membership.billing",
    text: "Process membership sign-ups, renewals, and rental/day-pass charges; issue receipts",
    agentType: "membership-billing",
    agentLabel: "Membership billing",
    teamHint: "cfo",
    frequency: "daily",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Membership/payment platform",
    cadence: "daily",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.expenses.categorize",
    text: "Tag facility and equipment expenses and flag anomalies",
    agentType: "expense-categorization",
    agentLabel: "Expense categorization",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10 approvals",
    handsTool: null,
    cadence: "nightly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.cashflow.forecast",
    text: "30/60/90-day cash-flow projection and runway alerts",
    agentType: "cashflow-forecast",
    agentLabel: "Cash-flow forecast",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "reports only",
    handsTool: null,
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cfo.tax.tracker",
    text: "Track tax deadlines and local business license renewals",
    agentType: "tax-deadline-tracker",
    agentLabel: "Tax-deadline tracker",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T1",
    autonomy: "locked",
    handsTool: null,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // Ops — the facility itself: bookings, membership tracking, upkeep, supplies.
  {
    id: "ops.booking.scheduler",
    text: "Manage the booking calendar for equipment, rooms, and rental slots — flag conflicts and double-bookings",
    agentType: "booking-scheduler",
    agentLabel: "Booking scheduler",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Booking platform",
    cadence: "daily",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "ops.membership.tracking",
    text: "Track active memberships, upcoming renewals, and lapsed members",
    agentType: "membership-tracking",
    agentLabel: "Membership tracking",
    teamHint: "ops",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: "Membership platform",
    cadence: "daily",
    batchable: true,
    triggerType: "threshold",
  },
  {
    id: "ops.facility.maintenance",
    text: "Monitor equipment/facility condition logs and flag overdue maintenance items",
    agentType: "facility-maintenance",
    agentLabel: "Facility maintenance",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "medium",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: null,
    cadence: "weekly",
    batchable: true,
    triggerType: "threshold",
  },
  {
    id: "ops.vendor.supplies",
    text: "Track supply/consumables orders and flag reorder points",
    agentType: "vendor-manager",
    agentLabel: "Vendor manager",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: null,
    cadence: "weekly",
    batchable: true,
    triggerType: "threshold",
  },
  {
    id: "ops.event.coordinator",
    text: "Compile and publish the class/event schedule — confirm instructor/host availability and room allocation, send attendee reminders",
    agentType: "event-coordinator",
    agentLabel: "Event coordinator",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Calendar",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },

  // CMO
  {
    id: "cmo.social.local",
    text: "Draft local social posts (new classes, open slots, member spotlights)",
    agentType: "social-manager",
    agentLabel: "Social manager",
    teamHint: "cmo",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Instagram/Facebook",
    cadence: "daily",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cmo.email.member",
    text: "Draft member newsletters and renewal/win-back campaigns",
    agentType: "email-marketing",
    agentLabel: "Email marketing",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Email",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cmo.seo.local",
    text: "Keep the Google Business listing and local SEO fresh",
    agentType: "seo-agent",
    agentLabel: "SEO agent",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: "Google Business",
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // Support
  {
    id: "support.triage.inbound",
    text: "Read inbound member messages/DMs, tag urgency, draft replies to known questions",
    agentType: "tier1-triage",
    agentLabel: "Tier-1 triage",
    teamHint: "support",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "known-answer replies",
    handsTool: "Shared inbox",
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "support.escalation.detect",
    text: "Detect upset members or complex cases and package context for the human",
    agentType: "escalation",
    agentLabel: "Escalation",
    teamHint: "support",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "always routes to human",
    handsTool: null,
    cadence: null,
    batchable: false,
    triggerType: "event",
  },

  // Compliance — safety/waivers/liability, attaches to CFO or Ops (Part 2).
  {
    id: "compliance.safety-waivers",
    text: "Manage member waivers and flag safety/liability concerns from incident reports for human legal/insurance review",
    agentType: "safety-waivers",
    agentLabel: "Safety & waivers",
    teamHint: "compliance",
    frequency: "monthly",
    stakes: "high",
    tier: "T3",
    autonomy: "locked",
    autonomyNote: "flags for human + user's own lawyer/insurer, never advises autonomously",
    handsTool: null,
    requiresProfessionalVerification: true,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // People — instructors/staff for classes and facility coverage.
  {
    id: "people.jobpost.write",
    text: "Draft job posts when hiring signals appear (instructors, front-desk, maintenance)",
    agentType: "job-post-writer",
    agentLabel: "Job-post writer",
    teamHint: "people",
    frequency: "adhoc",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    handsTool: null,
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "people.applicant.summarize",
    text: "Summarize applicants for human screening",
    agentType: "applicant-summarizer",
    agentLabel: "Applicant summarizer",
    teamHint: "people",
    frequency: "adhoc",
    stakes: "medium",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "assists screening, never auto-rejects — the human decides",
    handsTool: null,
    cadence: null,
    batchable: true,
    triggerType: "event",
  },
];

export const physicalSpaceTemplate: BusinessTemplate = {
  id: "physical-space",
  name: "Physical-space membership business",
  description:
    "A business built around a shared physical space or equipment — memberships, bookings/rentals, and " +
    "events/classes (gyms, makerspaces, coworking spaces, studios).",
  tasks,
  branchQuestions: [
    {
      id: "safetyRisk",
      prompt:
        "Does your space involve physical safety risk (e.g. climbing, fitness equipment), or is it purely space rental (e.g. coworking, studio time)?",
      kind: "single-select",
      options: [
        { value: "safety-risk", label: "Real physical safety risk" },
        { value: "low-risk", label: "Mostly space rental, low risk" },
      ],
    },
    {
      id: "classesOrSelfServe",
      prompt: "Do you offer classes/events, or purely self-serve access?",
      kind: "single-select",
      options: [
        { value: "classes-and-events", label: "Classes and events" },
        { value: "self-serve", label: "Self-serve access only" },
        { value: "both", label: "Both" },
      ],
    },
  ],
};
