import type { BusinessTemplate, TemplateTask } from "./types.js";
import { chiefOfStaffTask } from "./common.js";

// SaaS/software product, not yet built. Per Part 2's example ("SaaS idea,
// not built yet"): Product/Dev Lead is the heart (MVP-3) + CMO doing
// build-in-public content + CFO lite + Support handling the waitlist.
const tasks: TemplateTask[] = [
  chiefOfStaffTask,

  // Product/Dev — the heart
  {
    id: "productdev.spec.write",
    text: "Write feature specs from the founder's goals",
    agentType: "spec-writer",
    agentLabel: "Spec writer",
    teamHint: "product-dev",
    frequency: "weekly",
    stakes: "high",
    tier: "T3",
    autonomy: "earnable",
    handsTool: null,
  },
  {
    id: "productdev.build.propose",
    text: "Propose code changes through the sandboxed build pipeline",
    agentType: "build-agent",
    agentLabel: "Build agent",
    teamHint: "product-dev",
    frequency: "daily",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "code proposals only, zero production credentials",
    handsTool: "GitHub",
  },
  {
    id: "productdev.qa.smoketest",
    text: "Run automated smoke-tests on proposed changes",
    agentType: "qa-smoke-test",
    agentLabel: "QA/smoke-test agent",
    teamHint: "product-dev",
    frequency: "daily",
    stakes: "medium",
    tier: "T2",
    autonomy: "locked",
    handsTool: "GitHub",
  },
  {
    id: "productdev.deploy.coordinate",
    text: "Coordinate the staging preview and deploy pipeline",
    agentType: "deploy-coordinator",
    agentLabel: "Deploy coordinator",
    teamHint: "product-dev",
    frequency: "daily",
    stakes: "high",
    tier: "T1",
    autonomy: "locked",
    autonomyNote: "the human approves every production deploy, always",
    handsTool: "GitHub",
  },

  // CMO — build-in-public
  {
    id: "cmo.content.buildinpublic",
    text: "Draft build-in-public progress updates",
    agentType: "content-writer",
    agentLabel: "Content writer",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Twitter/X",
  },
  {
    id: "cmo.content.landing",
    text: "Write landing-page and launch copy in brand voice",
    agentType: "content-writer",
    agentLabel: "Content writer",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: null,
  },
  {
    id: "cmo.social.waitlist",
    text: "Draft platform-sized posts promoting the waitlist",
    agentType: "social-manager",
    agentLabel: "Social manager",
    teamHint: "cmo",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: null,
  },
  {
    id: "cmo.seo.landing",
    text: "Light keyword research and meta drafts for the landing page",
    agentType: "seo-agent",
    agentLabel: "SEO agent",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "reports",
    handsTool: null,
  },

  // CFO — lite
  {
    id: "cfo.invoicing.create",
    text: "Create invoices once paying subscribers exist",
    agentType: "invoicing",
    agentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Stripe",
  },
  {
    id: "cfo.expenses.categorize",
    text: "Tag expenses (hosting, tooling) and flag anomalies",
    agentType: "expense-categorization",
    agentLabel: "Expense categorization",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10 approvals",
    handsTool: null,
  },
  {
    id: "cfo.cashflow.runway",
    text: "Project runway against current burn",
    agentType: "cashflow-forecast",
    agentLabel: "Cash-flow forecast",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "reports only",
    handsTool: null,
  },

  // Support — waitlist
  {
    id: "support.waitlist.updates",
    text: "Draft waitlist confirmation and update messages",
    agentType: "onboarding",
    agentLabel: "Onboarding",
    teamHint: "support",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Email",
  },
  {
    id: "support.triage.inbound",
    text: "Read inbound questions from the waitlist/early users, draft replies to known questions",
    agentType: "tier1-triage",
    agentLabel: "Tier-1 triage",
    teamHint: "support",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "known-answer replies",
    handsTool: "Shared inbox",
  },
];

export const saasTemplate: BusinessTemplate = {
  id: "saas",
  name: "SaaS / software product",
  description: "A software product idea, including ones not yet built (MVP-3 build branch applies).",
  tasks,
};
