import type { BusinessTemplate, TemplateTask } from "./types.js";
import { chiefOfStaffTask } from "./common.js";

// Professional/local service business (consulting, bookkeeping, agencies).
// Per Part 2's example ("freelance bookkeeping service"): CFO + Sales as
// the heart of the org (qualifier/outreach/proposals) + Support that's
// onboarding-heavy + a Compliance sub-agent, with NO fulfillment and only
// minimal marketing.
//
// Delivery vs. CFO: this template's CFO tasks are strictly the business's
// OWN finance (its own invoices, its own expenses, its own taxes) using
// "own-backoffice" Hands scope. The paid work itself — the actual service
// being delivered to clients — belongs to "delivery" instead, scoped
// "client-facing". For a finance-adjacent service (bookkeeping, tax prep,
// financial consulting) this split matters most, since without it the
// paid deliverable would otherwise clump into the same categoryHint as
// back-office bookkeeping and inflate CFO's apparent size.
const tasks: TemplateTask[] = [
  chiefOfStaffTask,

  // CFO
  {
    id: "cfo.invoicing.create",
    text: "Create invoices for client retainers/projects",
    agentType: "invoicing",
    agentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Stripe",
    handsScope: "own-backoffice",
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.invoicing.remind",
    text: "Draft payment reminders matched to client history",
    agentType: "invoicing",
    agentLabel: "Invoicing",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "drafts only — sending stays locked",
    handsTool: "Stripe",
    handsScope: "own-backoffice",
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "cfo.expenses.categorize",
    text: "Tag business expenses and flag anomalies",
    agentType: "expense-categorization",
    agentLabel: "Expense categorization",
    teamHint: "cfo",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10 approvals",
    handsTool: null,
    cadence: "nightly",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "cfo.cashflow.forecast",
    text: "30/60/90-day cash-flow projection and runway alerts",
    agentType: "cashflow-forecast",
    agentLabel: "Cash-flow forecast",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T2",
    autonomy: "earnable",
    autonomyNote: "reports only",
    handsTool: null,
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "cfo.tax.tracker",
    text: "Track tax deadlines and prep the accountant handoff packet",
    agentType: "tax-deadline-tracker",
    agentLabel: "Tax-deadline tracker",
    teamHint: "cfo",
    frequency: "monthly",
    stakes: "medium",
    tier: "T1",
    autonomy: "locked",
    handsTool: null,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // Delivery — the paid work itself, distinct from CFO's own back-office
  // finance. Generic scaffold; the customize pass fills in what the paid
  // work actually is for this specific idea (e.g. bookkeeping reconciliation
  // for a bookkeeping service) and MUST tag those additions "delivery", not
  // "cfo" — even when the paid work happens to be finance-shaped.
  {
    id: "delivery.core.execute",
    text: "Do the core paid work for each client",
    agentType: "core-service-delivery",
    agentLabel: "Service delivery",
    teamHint: "delivery",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "this is the paid deliverable — never autonomous at MVP-0",
    handsTool: "Client-facing systems (per-client, scoped access)",
    handsScope: "client-facing",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "delivery.core.qa",
    text: "Check completed client work for accuracy before it goes out",
    agentType: "delivery-qa",
    agentLabel: "Delivery QA",
    teamHint: "delivery",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    handsTool: null,
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "delivery.core.handoff",
    text: "Package and send finished work to the client",
    agentType: "delivery-handoff",
    agentLabel: "Delivery handoff",
    teamHint: "delivery",
    frequency: "weekly",
    stakes: "medium",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Client-facing systems (per-client, scoped access)",
    handsScope: "client-facing",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },

  // Sales — the heart
  {
    id: "sales.qualifier.score",
    text: "Score inbound leads and enrich them from public info",
    agentType: "lead-qualifier",
    agentLabel: "Lead qualifier",
    teamHint: "sales",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    handsTool: "CRM",
    cadence: "daily",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "sales.outreach.draft",
    text: "Draft personalized first-touch and follow-up outreach",
    agentType: "outreach-drafter",
    agentLabel: "Outreach drafter",
    teamHint: "sales",
    frequency: "daily",
    stakes: "medium",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "sending, always",
    handsTool: "Email",
    cadence: "daily",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "sales.crm.hygiene",
    text: "Log interactions, update deal stages, flag stale deals",
    agentType: "crm-hygiene",
    agentLabel: "CRM hygiene",
    teamHint: "sales",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "eligible-early",
    autonomyNote: "after 10",
    handsTool: "CRM",
    cadence: "daily",
    batchable: true,
    triggerType: "cadence",
  },
  {
    id: "sales.proposal.build",
    text: "Build quotes/proposals from templates and deal context",
    agentType: "proposal-builder",
    agentLabel: "Proposal builder",
    teamHint: "sales",
    frequency: "weekly",
    stakes: "medium",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "sending",
    handsTool: "CRM",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },

  // Support — onboarding-heavy
  {
    id: "support.onboarding.welcome",
    text: "Draft welcome sequences for new clients",
    agentType: "onboarding",
    agentLabel: "Onboarding",
    teamHint: "support",
    frequency: "weekly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: "Email",
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "support.onboarding.setup",
    text: "Draft setup guides and check-in messages for new clients",
    agentType: "onboarding",
    agentLabel: "Onboarding",
    teamHint: "support",
    frequency: "weekly",
    stakes: "low",
    tier: "T2",
    autonomy: "earnable",
    handsTool: null,
    cadence: "weekly",
    batchable: false,
    triggerType: "cadence",
  },
  {
    id: "support.triage.inbound",
    text: "Read inbound client messages, tag urgency, draft replies to known questions",
    agentType: "tier1-triage",
    agentLabel: "Tier-1 triage",
    teamHint: "support",
    frequency: "daily",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    autonomyNote: "known-answer replies",
    handsTool: "Shared inbox",
    cadence: null,
    batchable: false,
    triggerType: "event",
  },
  {
    id: "support.escalation.detect",
    text: "Detect complex or upset cases and package context for the human",
    agentType: "escalation",
    agentLabel: "Escalation",
    teamHint: "support",
    frequency: "weekly",
    stakes: "high",
    tier: "T2",
    autonomy: "locked",
    autonomyNote: "always routes to human",
    handsTool: null,
    cadence: null,
    batchable: false,
    triggerType: "event",
  },

  // Compliance sub-agent (attaches to CFO — Part 2)
  {
    id: "compliance.review",
    text: "Flag contract red-flags and track regulation deadlines",
    agentType: "compliance-review",
    agentLabel: "Compliance sub-agent",
    teamHint: "compliance",
    frequency: "monthly",
    stakes: "high",
    tier: "T3",
    autonomy: "locked",
    autonomyNote: "flags for human + user's own lawyer/accountant, never advises autonomously",
    handsTool: null,
    requiresProfessionalVerification: true,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // Minimal marketing
  {
    id: "cmo.social.expertise",
    text: "Draft occasional posts establishing professional expertise",
    agentType: "social-manager",
    agentLabel: "Social manager",
    teamHint: "cmo",
    frequency: "monthly",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: null,
    cadence: "monthly",
    batchable: false,
    triggerType: "cadence",
  },

  // Light scheduling (client calls)
  {
    id: "ops.scheduling.calls",
    text: "Manage calendar, booking confirmations and reminders for client calls",
    agentType: "scheduling",
    agentLabel: "Scheduling",
    teamHint: "ops",
    frequency: "weekly",
    stakes: "low",
    tier: "T1",
    autonomy: "earnable",
    handsTool: "Calendar",
    cadence: "weekly",
    batchable: true,
    triggerType: "cadence",
  },
];

export const serviceTemplate: BusinessTemplate = {
  id: "service",
  name: "Service business",
  description: "Professional or local services sold to consumers or businesses (consulting, bookkeeping, agencies).",
  tasks,
  branchQuestions: [
    {
      id: "billingModel",
      prompt: "How do you bill clients?",
      kind: "single-select",
      options: [
        { value: "hourly", label: "Hourly" },
        { value: "retainer", label: "Monthly retainer" },
        { value: "per-project", label: "Per project" },
        { value: "mixed", label: "A mix of these" },
      ],
    },
    {
      id: "deliveryMode",
      prompt: "Is delivery mostly remote or in person?",
      kind: "single-select",
      options: [
        { value: "remote", label: "Remote" },
        { value: "in-person", label: "In person" },
        { value: "mixed", label: "A mix of both" },
      ],
    },
  ],
};
